services:
  nginx:
    container_name: nginx
    build: ./frontend
    ports:
      - "8443:443"
    env_file:
      - .env
    networks:
      - frontend_net
    restart: on-failure
    volumes:
      - ./frontend/html:/usr/share/nginx/html:ro

networks:
  frontend_net:
    name: frontend_net
