services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    env_file:
      - .env
    networks:
      - frontend_net
    restart: on-failure

networks:
  frontend_net:
    driver: bridge
