services:
  nginx:
    container_name: nginx
    build: ./frontend
    ports:
      - 443:443
    env_file:
      - .env  
    networks:
      - transcendence_net 
    restart: on-failure 
    volumes:
      - ./frontend/www/:/usr/share/nginx/html:ro
      - ./backend/static:/usr/src/app/static:ro

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - transcendence_net

  db:
    image: postgres:13
    container_name: postgres
    restart: on-failure
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence_net

networks:
  transcendence_net:
    name: transcendence_net

volumes:
  postgres_data: